export { AdministracionService } from './services/administracion.service'
//export { BannerService } from './services/banner.service'
export { GlobalService } from './services/global.service'
export { StudentService } from './services/student.service'
export { UniversityService } from './services/university.service'
export { AlertService } from './services/alert.service'
export { PagerService } from './services//pager.service'